data:
  dataset_name_or_path: ./data/midjourney-v52-mar
  image_column: image
  prompt_column:
    - improved_prompt
    - prompt
  num_workers: 8
  center_crop: False
  random_flip: True
  proportion_empty_prompts: 0.1
  multi_aspect_training: True
  local_shuffle_buffer_size: 128
  prefetch_batches: 4

model:
  model_name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"

optimizer:
  learning_rate: 0.0001
  auto_scale_lr: False
  weight_decay: 1e-2
  lr_scheduler: constant
  lr_warmup_steps: 0

trainer:
  class_path: omni_diffusion.trainers.sdxl_ray_trainer.SDXLRayTrainer
  init_args:
    project_name: "openjourney-xl"
    output_dir: ./outputs/openjourney-xl5
    num_devices: 8
    max_steps: 200000
    train_batch_size: 4
    validation_every_n_steps: 10000000
    validation_prompt: "cute dragon creature"
    num_validation_samples: 0
    gradient_accumulation_steps: 64
    gradient_checkpointing: False
    checkpointing_every_n_steps: 500
    max_checkpoints: 10
    seed: 42
    use_ema: True
    mixed_precision: fp16
    use_xformers: True
    noise_offset: 0.05
    use_deepspeed: True
    resume_from_checkpoint: latest
    pipeline_cls: StableDiffusionXLPipeline

logging:
  logging_dir: logs
  report_to: wandb
