data:
  dataset_name_or_path: ./data/midjourney-v52-mar
  image_column: image
  prompt_column:
    - improved_prompt
    - prompt
  num_workers: 8
  center_crop: False
  random_flip: True
  proportion_empty_prompts: 0.1
  multi_aspect_training: False

model:
  model_name_or_path: "nota-ai/bk-sdm-tiny"

optimizer:
  learning_rate: 0.0001
  auto_scale_lr: False
  weight_decay: 1e-2
  lr_scheduler: constant

trainer:
  class_path: omni_diffusion.trainers.sd_trainer.StableDiffusionTrainer
  init_args:
    project_name: "bk-sdm-tiny"
    output_dir: ./outputs/bk-sdm-tiny
    num_devices: 8
    max_steps: 200000
    train_batch_size: 8
    validation_every_n_steps: 10000000
    validation_prompt: "cute dragon creature"
    num_validation_samples: 0
    gradient_accumulation_steps: 32
    gradient_checkpointing: False
    checkpointing_every_n_steps: 1000
    max_checkpoints: 10
    seed: 42
    use_ema: True
    mixed_precision: fp16
    use_xformers: True
    use_deepspeed: True
    resume_from_checkpoint: latest

logging:
  logging_dir: logs
  report_to: wandb
