data:
  dataset_name_or_path: /home/mingyang/projs/OmniDiffusion/data/midjourney-v52-mar-mds/1024_1024_018653673
  image_column: image
  prompt_column:
    - improved_prompt
    - prompt
  num_workers: 32
  resolution: 512
  center_crop: True
  random_flip: True
  proportion_empty_prompts: 0.1
  multi_aspect_training: False
  local_shuffle_buffer_size: 256
  prefetch_batches: 8

model:
  model_name_or_path: nota-ai/bk-sdm-tiny
  unet_checkpoint_path: /home/mingyang/projs/OmniDiffusion/outputs/bk-sdm-tiny/checkpoint-5000/unet_ema

optimizer:
  learning_rate: 0.0001
  auto_scale_lr: False
  weight_decay: 1e-2
  lr_scheduler: constant_with_warmup
  lr_warmup_steps: 500

trainer:
  class_path: omni_diffusion.trainers.sd_distiller.StableDiffusionStepDistiller
  init_args:
    project_name: "bk-sdm-tiny"
    output_dir: ./outputs/bk-sdm-tiny-step-distill-16-8
    num_devices: 8
    max_steps: 200000
    train_batch_size: 64
    validation_every_n_steps: 10000000
    validation_prompt: "cute dragon creature"
    num_validation_samples: 0
    gradient_accumulation_steps: 4
    gradient_checkpointing: False
    checkpointing_every_n_steps: 1000
    max_checkpoints: 10
    seed: 82
    use_ema: True
    mixed_precision: fp16
    use_xformers: True
    use_deepspeed: True
    resume_from_checkpoint: latest
    prediction_type: v_prediction
    snr_gamma: 5.0
    num_ddim_steps: 16
    guidance_rescale: 0.7
    cfg_aware_distillation_prob: 0.2

logging:
  logging_dir: logs
  report_to: wandb
